// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: handlerspub.proto

package grpc_hanglers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientRMQhandlersClient is the client API for ClientRMQhandlers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientRMQhandlersClient interface {
	PublishText(ctx context.Context, in *PublishTextRequest, opts ...grpc.CallOption) (*PublishTextResponse, error)
}

type clientRMQhandlersClient struct {
	cc grpc.ClientConnInterface
}

func NewClientRMQhandlersClient(cc grpc.ClientConnInterface) ClientRMQhandlersClient {
	return &clientRMQhandlersClient{cc}
}

func (c *clientRMQhandlersClient) PublishText(ctx context.Context, in *PublishTextRequest, opts ...grpc.CallOption) (*PublishTextResponse, error) {
	out := new(PublishTextResponse)
	err := c.cc.Invoke(ctx, "/proto.ClientRMQhandlers/PublishText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientRMQhandlersServer is the server API for ClientRMQhandlers service.
// All implementations must embed UnimplementedClientRMQhandlersServer
// for forward compatibility
type ClientRMQhandlersServer interface {
	PublishText(context.Context, *PublishTextRequest) (*PublishTextResponse, error)
	mustEmbedUnimplementedClientRMQhandlersServer()
}

// UnimplementedClientRMQhandlersServer must be embedded to have forward compatible implementations.
type UnimplementedClientRMQhandlersServer struct {
}

func (UnimplementedClientRMQhandlersServer) PublishText(context.Context, *PublishTextRequest) (*PublishTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishText not implemented")
}
func (UnimplementedClientRMQhandlersServer) mustEmbedUnimplementedClientRMQhandlersServer() {}

// UnsafeClientRMQhandlersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientRMQhandlersServer will
// result in compilation errors.
type UnsafeClientRMQhandlersServer interface {
	mustEmbedUnimplementedClientRMQhandlersServer()
}

func RegisterClientRMQhandlersServer(s grpc.ServiceRegistrar, srv ClientRMQhandlersServer) {
	s.RegisterService(&ClientRMQhandlers_ServiceDesc, srv)
}

func _ClientRMQhandlers_PublishText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRMQhandlersServer).PublishText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClientRMQhandlers/PublishText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRMQhandlersServer).PublishText(ctx, req.(*PublishTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientRMQhandlers_ServiceDesc is the grpc.ServiceDesc for ClientRMQhandlers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientRMQhandlers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClientRMQhandlers",
	HandlerType: (*ClientRMQhandlersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishText",
			Handler:    _ClientRMQhandlers_PublishText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handlerspub.proto",
}
